# Generated by Django 2.2.1 on 2019-05-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_auto_20190522_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtype',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
