# Generated by Django 2.2.1 on 2019-05-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_auto_20190522_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestatus',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
